### ISSUE TITLE
Don't know how to setup the mac address

### ISSUE THREAD

**Issue by ccdodo** [grotius-cnc/LINUX_RTOS#2]
Hi,I need help. I have installed the skynet software ,but i can't start the ethercat master. I use dmesg to find the error is " ETHERCAT ERROR: MAC address may not be empty" . I have set the mac address in file:  /usr/local/share/ethercat/ethercat

What should i do to solve this problem. Thank you!

**Comment by ccdodo** [comment]
I have solve this problem.

**Comment by malefs** [comment]
how did you solve this?
